Feat/schedule appointment
jorgelucasalm/petcare pull request #58
Opened 2022-05-02 23:41 UTC by dEgito

Boy, é mais um modal
Ele vai ser ativado a partir da tela Home (que ainda tá aguardando pra subir pra develop)

2022-05-02 23:42 UTC, dEgito commented
Lembrando que não tá salvando no banco ainda

2022-05-05 03:14 UTC, jorgelucasalm requested changes
Fico massa o design, so tem detalhes em questão de semantica para pontuar apenas

2022-05-05 03:14 UTC, jorgelucasalm commented on src/pages/ScheduleAppointment/index.js
> +        <Card>
Seria interessante ao inves do nome card ser um Form visto que essa é a funcionalidade dele. Alem do nome mudar o tipo para form no styled

2022-05-05 03:14 UTC, jorgelucasalm commented on src/pages/ScheduleAppointment/index.js
> +            <p>Selecione uma categoria:</p>
Titulos antes de um input/select semanticamente são label's

2022-05-09 12:58 UTC, merged